### PR TITLE
Fixed the unused variable

### LINKED ISSUE #1: fix unused variable x in HelloWorld.Java
fix unused variable x in HelloWorld.Java

---
int x
---

### PR DESCRIPTION
**Pull request by mkathera**
Fixes #1

### CODE REVIEW

File: HelloWorld.java [hunk 1]
```diff
@@ -3,7 +3,6 @@
     public static void main(String[] args) {
         // Prints "Hello, World" to the terminal window.
         System.out.println("Hello, World");
-	int x;
```
Comment (mkathera) [inline HelloWorld.java:6]: Thank you
